### ISSUE TITLE
aemet: Error on device update!

### ISSUE THREAD

**Issue by gargomoma** [outon/HomeAssistant-AEMET#11]
Hola buenas! 
Últimamente estoy teniendo problemas con el addon, pero no entiendo qué le está pasando.
He intentado seguir el código, pero no llego a estar 100% seguro.

Puede ser que no sea capaz de obtener las coordenadas?

Este es el error:
`aemet: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 312, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/aemet/weather.py", line 363, in update
    self._aemet.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/aemet/aemet.py", line 794, in update
    self.weather_stations.update_distance(self.location)
  File "/config/custom_components/aemet/aemet.py", line 380, in update_distance
    location, (self.nearest[ATTR_LATITUDE], self.nearest[ATTR_LONGITUDE])
TypeError: 'NoneType' object is not subscriptable`

Mi configuración no tiene nada en especial, las almohadillas son porque también he probado todas las opciones, pero no funciona con ninguna de ellas.
`weather:
  platform: aemet
  #name: aemet_weather
  api_key: API_KEY
  #latitude: 40.22
  #longitude: -3.65
  #weather_station: 3195`

Estoy en la versión 0.106.1

Muchas gracias!

**Comment by gargomoma** [comment]
Acabo de borrar la carpeta de archivos temporales y ha vuelto a funcionar.
Tal vez los permisos de lectura/escritura cambiaron.

Si vuelve a pasar reabro.
Un saludo!

**Comment by outon** [comment]
Tengo que deshacerme de esa carpeta temporal... me da mas problemas que beneficios
