### ISSUE TITLE
Not working on last version of HA

### ISSUE THREAD

**Issue by ajtudela** [outon/HomeAssistant-AEMET#9]
Hi, I have this error:
`aemet: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 312, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/aemet/weather.py", line 396, in update
    self._aemet.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/aemet/aemet.py", line 1139, in update
    api_client=self.api_client,
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/aemet/aemet.py", line 860, in update
    data = self._update_forecast()
  File "/config/custom_components/aemet/aemet.py", line 848, in _update_forecast
    clean_data = self._refactor_forecast(raw_data)
  File "/config/custom_components/aemet/aemet.py", line 789, in _refactor_forecast
    transformed_data[fecha][horas] = value
KeyError: '2020-04-02T00:00:00'`

**Comment by outon** [comment]
Buenos días Alberto.

Hace un par de meses la AEMET decidió comenzar a usar la ISO-8601 para el campo fecha.

Creo que he corregido los errores en el commit [Fix date received from AEMET. Now they comply with ISO8601](https://github.com/outon/HomeAssistant-AEMET/commit/a5262fd741132f31673b4564fc47355070de6bc4). Pero pudiera ser que tuviese alguna regresión o que hayan modificado la fecha en más lugares.

Por favor, actualiza el código con la última versión disponible en GitHub. Si sigue ocurriendo el error necesitaría te solicitaría más detalles.

**Comment by ajtudela** [comment]
Buenas, he probado la ultima version de github, y ahora me sale otro error diferente. 
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 312, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/aemet/weather.py", line 357, in update
    self._aemet.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/aemet/aemet.py", line 794, in update
    self.weather_stations.update_distance(self.location)
  File "/config/custom_components/aemet/aemet.py", line 377, in update_distance
    (distance, self.nearest) = self._nearest_location(location)
  File "/config/custom_components/aemet/aemet.py", line 360, in _nearest_location_iterate
    (distance, closest_location) = nearest_location(list_locations, location)
  File "/config/custom_components/aemet/aemet.py", line 342, in nearest_location
    float(point[ATTR_LATITUDE]),
KeyError: 'latitude'`

**Comment by outon** [comment]
Hola

Me he instalado una versión limpia y no logro reproducir el error. Necesitaría conocer las coordenadas geográficas que tienes establecidas bien en la configuración del componente bien en la configuración de HA. 

Está buscando la ubicación de la estación meteorológica más cercana a tu ubicación y está fallando. Pero no logro obtener un caso de uso que pueda reproducir el error.

Un saludo.

**Comment by ajtudela** [comment]
Buenas, en la configuración del componente solo tengo puesto la clave de la api y la estación "6172X". En las coordenadas de HA tengo lo siguiente: latitud: 36.714110, longitud:-4.430925.

Muchas gracias por tu ayuda

**Comment by outon** [comment]
Estoy rescribiendo código para validar los datos de entrada de AEMET.

Mientras tanto, y como workaround borra el contenido de la carpeta `/config/aemet` debe haber un par de ficheros con extensión `json`. 

Hay información que se cachea,.. como lista de estaciones y ciudades para no tener que recuperar la información. Si ha venido mal o la he guardado mal entonces hasta que no pasan varios días no se limpia la caché.

Si con eso no funciona es que se está recuperando información no válida (y para eso la validación que estoy preparando).

Un saludo

**Comment by ajtudela** [comment]
Buenas, parece ser que borrando la caché con la estación meteorológica puesta pilla los datos perfectamente.

Muchas gracias por la ayuda y siento los inconvenientes.

Una pregunta, es posible sacar otros datos como la presión del aire, etc de la AEMET?

**Comment by outon** [comment]
La información que se obtiene es la que informa la AEMET. Esta información depende de la estación meteorológica que informa de los datos.

En el fichero de [constantes](https://github.com/outon/HomeAssistant-AEMET/blob/master/aemet/const.py) se muestra los valores que puede recoger una estación meteorológica.

La palabra clave es *puede*, entre los datos está la presión atmosférica (pres) pero no todas las estaciones las publican.
